/*
        *  AUTO-GENERATED FILE.  DO NOT MODIFY.
        *
        *  This class was automatically generated by the
        *  aapt tool from the resource data it found.  It  should not be modified by hand.
*/
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
var _a, _b, _c, _d, _e;
/* Generated Code Do Not Modify */
import { Object } from '../../../../java/lang/Object.js';
//Current folder imports from return types, extended types, and scope (deduplicated)
export class R extends Object {
}
//inner= member=true isStatic=static
R.attr = class extends Object {
};
//inner= member=true isStatic=static
R.drawable = (_a = class extends Object {
    },
    __setFunctionName(_a, "drawable"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _a.testgamedemo_icon = 0x7f020000,
    _a.testgamedemo_wait_256_by_256 = 0x7f020001,
    _a);
//inner= member=true isStatic=static
R.id = (_b = class extends Object {
    },
    __setFunctionName(_b, "id"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _b.ad_area_bottom = 0x7f060002,
    _b.ad_area_left = 0x7f060003,
    _b.ad_area_right = 0x7f060004,
    _b.ad_area_top = 0x7f060001,
    _b.testgamedemo = 0x7f060000,
    _b.testgamedemo_gl = 0x7f060005,
    _b);
//inner= member=true isStatic=static
R.layout = (_c = class extends Object {
    },
    __setFunctionName(_c, "layout"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _c.testgamedemo_ad_overlay_layout = 0x7f030000,
    _c.testgamedemo_gl_layout = 0x7f030001,
    _c.testgamedemo_layout = 0x7f030002,
    _c);
//inner= member=true isStatic=static
R.raw = (_d = class extends Object {
    },
    __setFunctionName(_d, "raw"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _d.error = 0x7f040000,
    _d.licenseinitdata = 0x7f040001,
    _d.partner = 0x7f040002,
    _d.select = 0x7f040003,
    _d.test = 0x7f040004,
    _d.testgamedemo_wait_256_by_256 = 0x7f040005,
    _d.ouya_a = 0x7f040012,
    _d.ouya_key = 0x7f040013,
    _d.ouya_o = 0x7f040014,
    _d.ouya_u = 0x7f040015,
    _d.ouya_y = 0x7f040016,
    _d.touch_button_128_by_128 = 0x7f040026,
    _d.touch_button_64_by_64 = 0x7f040027,
    _d.touch_button_create_128_by_128 = 0x7f040028,
    _d.touch_button_create_64_by_64 = 0x7f040029,
    _d.touch_button_down_arrow_128_by_128 = 0x7f04002a,
    _d.touch_button_down_arrow_64_by_64 = 0x7f04002b,
    _d.touch_button_generic_action_128_by_128 = 0x7f04002c,
    _d.touch_button_generic_action_64_by_64 = 0x7f04002d,
    _d.touch_button_join_128_by_128 = 0x7f04002e,
    _d.touch_button_join_64_by_64 = 0x7f04002f,
    _d.touch_button_leave_128_by_128 = 0x7f040030,
    _d.touch_button_leave_64_by_64 = 0x7f040031,
    _d.touch_button_login_128_by_128 = 0x7f040032,
    _d.touch_button_login_64_by_64 = 0x7f040033,
    _d.touch_button_next_128_by_128 = 0x7f040034,
    _d.touch_button_next_64_by_64 = 0x7f040035,
    _d.touch_button_refresh_128_by_128 = 0x7f040036,
    _d.touch_button_refresh_64_by_64 = 0x7f040037,
    _d.touch_button_start_128_by_128 = 0x7f040038,
    _d.touch_button_start_64_by_64 = 0x7f040039,
    _d.touch_button_add_local_player_128_by_128 = 0x7f040038,
    _d.touch_button_add_local_player_64_by_64 = 0x7f040039,
    _d.touch_button_strafe_left_arrow_128_by_128 = 0x7f04003a,
    _d.touch_button_strafe_left_arrow_64_by_64 = 0x7f04003b,
    _d.touch_button_strafe_right_arrow_128_by_128 = 0x7f04003c,
    _d.touch_button_strafe_right_arrow_64_by_64 = 0x7f04003d,
    _d.touch_button_turn_left_arrow_128_by_128 = 0x7f04003e,
    _d.touch_button_turn_left_arrow_64_by_64 = 0x7f04003f,
    _d.touch_button_turn_right_arrow_128_by_128 = 0x7f040040,
    _d.touch_button_turn_right_arrow_64_by_64 = 0x7f040041,
    _d.touch_button_up_arrow_128_by_128 = 0x7f040042,
    _d.touch_button_up_arrow_64_by_64 = 0x7f040043,
    _d.touch_button_generic_action_arrow_64_by_64 = 0x7f040009,
    _d);
//inner= member=true isStatic=static
R.string = (_e = class extends Object {
    },
    __setFunctionName(_e, "string"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _e.progressbar_in_title_string = 0x7f050001,
    _e.testgamedemo_app_name = 0x7f050000,
    _e);
