<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <groupId>org.allbinary.game</groupId>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>AllBinaryGameClientNoPlatformJavaDocJs</artifactId>
    <packaging>jar</packaging>
    <!-- AllBinary Platform Version Start -->
    <version>1.0.0-SNAPSHOT</version>
    <!-- AllBinary Platform Version End -->

    <name>AllBinaryGameClientNoPlatformJavaDocJs</name>
    <url>http://www.allbinary.com/</url>

    <properties>
        <inputPath2>src\main\java\</inputPath2>
        <inputPath>target\dependency\</inputPath>
        <outputPath>..\AllBinaryGameClientNoPlatformJavaDocApplicationM\src\main\java\</outputPath>
    </properties>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingJ2MEAllJs</artifactId>

<!--
<artifactId>LoggingJ2MEAllJs</artifactId>
<artifactId>LoggingNoneJs</artifactId>
<artifactId>LoggingJ2MEExceptionJs</artifactId>
<artifactId>LoggingRemoteExceptionJs</artifactId>

-->

            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameInputMEKeyOnlyJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AdvertisementClientNoneJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary.game.multiplayer</groupId>
            <artifactId>AllBinaryGameClientBaseNullJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NoGyroSensorJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <!--        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MotionGestureJavaLibraryJs</artifactId>
            
        </dependency>
        -->
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchScreenJ2MENoneJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchJ2MENoneJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <!--
            <artifactId>TouchJ2MEJavaLibraryJs</artifactId>
            <artifactId>TouchJ2MENoneJavaLibraryJs</artifactId>
            -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOnJ2MEPlatformJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <exclusions>
                <exclusion>
                    <artifactId>OpenGLNoneJavaLibraryJs</artifactId>
                    <groupId>org.allbinary</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NullCustomUIJavaLibraryJs</artifactId>
            <!--
            <artifactId>MicroEmulatorCustomUIJavaLibraryJs</artifactId>
            <artifactId>NullCustomUIJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NoGameLicensingJavaLibraryJs</artifactId>
            <!--
                <artifactId>NoGameLicensingJavaLibraryJs</artifactId>
                <artifactId>LicensedGameDemoJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <artifactId>BasicPlayerJavaLibraryJs</artifactId>
                    <groupId>org.allbinary</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameLicensingOnlyDemoJavaLibraryJs</artifactId>
            <!--
                <artifactId>GameLicensingOnlyNormalJavaLibraryJs</artifactId>
                <artifactId>GameLicensingOnlyDemoJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>HardCodedLicenseInitInfoJavaLibraryJs</artifactId>
            <!--
            <artifactId>HardCodedLicenseInitInfoJavaLibraryJs</artifactId>
            <artifactId>FileLicenseInitInfoJavaLibraryJs</artifactId>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>YourSecurityJavaLibraryJs</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FileJ2SEJavaLibraryJs</artifactId>
        </dependency>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>VectorAnimationJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <exclusions>
                <exclusion>
                    <artifactId>GraphBaseJavaLibraryJs</artifactId>
                    <groupId>org.graph</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>BasicPlayerJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchButtonJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MotionGestureJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>
                
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchButtonMappingJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>
                
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NotDeviceSpecificNoMediaMIDP1LibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>
        
    </dependencies>


    <build>

        <plugins>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <classifier>sources</classifier>
                            <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
                            <!--
                            <outputDirectory>${project.build.directory}/sources</outputDirectory>
                            -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Delete output directory -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-pluginJs</artifactId>
                <version>2.4.1</version>
                <configuration>
                    <followSymLinks>false</followSymLinks>
                    <filesets>
                        <fileset>
                            <directory>${outputPath}</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
      
            <plugin>
                <artifactId>maven-resources-pluginJs</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${outputPath}</outputDirectory>
                            <resources>          
                                <resource>
                                    <directory>${inputPath}</directory>
                                    <filtering>true</filtering>
                                </resource>
                                <resource>
                                    <directory>${inputPath2}</directory>
                                    <filtering>true</filtering>
                                </resource>
                                <!--
                                -->                
                            </resources>              
                        </configuration>            
                    </execution>
                </executions>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>clean-js-files</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <configuration>
                            <excludeDefaultDirectories>true</excludeDefaultDirectories>
                            <filesets>
                                <fileset>
                                    <directory>${basedir}/src</directory>
                                    <includes>
                                        <include>**/*.js</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <id>npm-install-typescript</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <arguments>
                                <argument>/c</argument>
                                <argument>npm</argument>
                                <argument>install</argument>
                                <argument>typescript</argument>
                                <argument>--no-save</argument>
                                <argument>--no-audit</argument>
                                <argument>--no-fund</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>tsc-compile</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <!-- Uses the path from tsconfig.json instead of -p path; ignore tsc errors so the build continues -->
                            <arguments>
                                <argument>/c</argument>
<!--                                <argument>npx tsc</argument>-->
                                <argument>npx tsc || exit 0</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

