/*
        *  AUTO-GENERATED FILE.  DO NOT MODIFY.
        *
        *  This class was automatically generated by the
        *  aapt tool from the resource data it found.  It  should not be modified by hand.
*/
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
var _a, _b, _c, _d;
/* Generated Code Do Not Modify */
import { Object } from '../../../../java/lang/Object.js';
//Current folder imports from return types, extended types, and scope (deduplicated)
export class R extends Object {
}
//inner= member=true isStatic=static
R.attr = class extends Object {
};
//inner= member=true isStatic=static
R.drawable = class extends Object {
};
//inner= member=true isStatic=static
R.id = (_a = class extends Object {
    },
    __setFunctionName(_a, "id"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _a.custom_web_view = 0x7f050000,
    _a.ad_area_bottom = 0x7f060002,
    _a.ad_area_left = 0x7f060003,
    _a.ad_area_right = 0x7f060004,
    _a.ad_area_top = 0x7f060001,
    _a);
//inner= member=true isStatic=static
R.layout = (_b = class extends Object {
    },
    __setFunctionName(_b, "layout"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _b.webview_layout = 0x7f020000,
    _b);
//inner= member=true isStatic=static
R.raw = (_c = class extends Object {
    },
    __setFunctionName(_c, "raw"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _c.about = 0x7f030000,
    _c.privacy_policy = 0x7f030001,
    _c.error = 0x7f040000,
    _c.licenseinitdata = 0x7f040001,
    _c.partner = 0x7f040002,
    _c.select = 0x7f040003,
    _c.test = 0x7f040004,
    _c.testgamedemo_wait_256_by_256 = 0x7f040005,
    _c.touch_button_128_by_128 = 0x7f040026,
    _c.touch_button_64_by_64 = 0x7f040027,
    _c.touch_button_down_arrow_128_by_128 = 0x7f04002a,
    _c.touch_button_down_arrow_64_by_64 = 0x7f04002b,
    _c.touch_button_generic_action_128_by_128 = 0x7f04002c,
    _c.touch_button_generic_action_64_by_64 = 0x7f04002d,
    _c.touch_button_start_128_by_128 = 0x7f040038,
    _c.touch_button_start_64_by_64 = 0x7f040039,
    _c.touch_button_strafe_left_arrow_128_by_128 = 0x7f04003a,
    _c.touch_button_strafe_left_arrow_64_by_64 = 0x7f04003b,
    _c.touch_button_strafe_right_arrow_128_by_128 = 0x7f04003c,
    _c.touch_button_strafe_right_arrow_64_by_64 = 0x7f04003d,
    _c.touch_button_turn_left_arrow_128_by_128 = 0x7f04003e,
    _c.touch_button_turn_left_arrow_64_by_64 = 0x7f04003f,
    _c.touch_button_turn_right_arrow_128_by_128 = 0x7f040040,
    _c.touch_button_turn_right_arrow_64_by_64 = 0x7f040041,
    _c.touch_button_up_arrow_128_by_128 = 0x7f040042,
    _c.touch_button_up_arrow_64_by_64 = 0x7f040043,
    _c.ouya_a = 0x7f040012,
    _c.ouya_o = 0x7f040014,
    _c.ouya_u = 0x7f040015,
    _c.ouya_y = 0x7f040016,
    _c.ouya_key = 0x7f040013,
    _c.google_key = 0x7f040013,
    _c);
//inner= member=true isStatic=static
R.string = (_d = class extends Object {
    },
    __setFunctionName(_d, "string"),
    /*Static stuff is not allowed for TypeScript inner classes*/
    _d.progressbar_in_title_string = 0x7f050001,
    _d);
